{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/10\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-04-17 14:45:23.380737: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:429] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR\n",
      "2023-04-17 14:45:23.380764: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at conv_ops.cc:1068 : UNIMPLEMENTED: DNN library is not found.\n",
      "2023-04-17 14:45:23.380774: I tensorflow/core/common_runtime/executor.cc:1197] [/job:localhost/replica:0/task:0/device:GPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): UNIMPLEMENTED: DNN library is not found.\n",
      "\t [[{{node sequential_1/conv1d_1/Conv1D}}]]\n"
     ]
    },
    {
     "ename": "UnimplementedError",
     "evalue": "Graph execution error:\n\nDetected at node 'sequential_1/conv1d_1/Conv1D' defined at (most recent call last):\n    File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/ipykernel_launcher.py\", line 17, in <module>\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 725, in start\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 215, in start\n    File \"/usr/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/usr/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/usr/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3006, in run_cell\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3061, in _run_cell\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3266, in run_cell_async\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3445, in run_ast_nodes\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3505, in run_code\n    File \"/tmp/ipykernel_1360394/2310772659.py\", line 34, in <module>\n      data.cnn()\n    File \"/tmp/ipykernel_1360394/2310772659.py\", line 30, in cnn\n      model.fit(self.dataset.X_train.reshape(-1, 800, 1), self.dataset.y_train, epochs=epochs, batch_size=batch_size, validation_data=(self.dataset.X_test.reshape(-1, 800, 1), self.dataset.y_test))\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      except Exception as e:  # pylint: disable=broad-except\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1685, in fit\n      **kwargs: Unused at this time.\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1284, in train_function\n      only. Maximum number of processes to spin up\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1268, in step_function\n      Number of samples per validation batch.\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1249, in run_step\n      `tf.data` dataset, and 'steps_per_epoch'\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1050, in train_step\n      \"\"\"Runs a training execution with a single step.\"\"\"\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      except Exception as e:  # pylint: disable=broad-except\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/training.py\", line 558, in __call__\n      `y_pred` should have shape `(batch_size, d0, .. dN)`.\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      except Exception as e:  # pylint: disable=broad-except\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1145, in __call__\n      @input_spec.setter\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 96, in error_handler\n      raise e\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/sequential.py\", line 412, in call\n      for layer in super(Sequential, self).layers:\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 512, in call\n      # Layers expect shapes to be tuples for `compute_output_shape`.\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 669, in _run_internal_graph\n      try:\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      except Exception as e:  # pylint: disable=broad-except\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1145, in __call__\n      @input_spec.setter\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 96, in error_handler\n      raise e\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/layers/convolutional/base_conv.py\", line 290, in call\n      ]\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/layers/convolutional/base_conv.py\", line 262, in convolution_op\n      def _apply_fn(o):\nNode: 'sequential_1/conv1d_1/Conv1D'\nDNN library is not found.\n\t [[{{node sequential_1/conv1d_1/Conv1D}}]] [Op:__inference_train_function_1553]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mUnimplementedError\u001b[0m                        Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[2], line 34\u001b[0m\n\u001b[1;32m     30\u001b[0m         model\u001b[39m.\u001b[39mfit(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdataset\u001b[39m.\u001b[39mX_train\u001b[39m.\u001b[39mreshape(\u001b[39m-\u001b[39m\u001b[39m1\u001b[39m, \u001b[39m800\u001b[39m, \u001b[39m1\u001b[39m), \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdataset\u001b[39m.\u001b[39my_train, epochs\u001b[39m=\u001b[39mepochs, batch_size\u001b[39m=\u001b[39mbatch_size, validation_data\u001b[39m=\u001b[39m(\u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdataset\u001b[39m.\u001b[39mX_test\u001b[39m.\u001b[39mreshape(\u001b[39m-\u001b[39m\u001b[39m1\u001b[39m, \u001b[39m800\u001b[39m, \u001b[39m1\u001b[39m), \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdataset\u001b[39m.\u001b[39my_test))\n\u001b[1;32m     33\u001b[0m data \u001b[39m=\u001b[39m Dataset()\n\u001b[0;32m---> 34\u001b[0m data\u001b[39m.\u001b[39;49mcnn()\n",
      "Cell \u001b[0;32mIn[2], line 30\u001b[0m, in \u001b[0;36mDataset.cnn\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m     27\u001b[0m model\u001b[39m.\u001b[39mcompile(loss\u001b[39m=\u001b[39m\u001b[39m'\u001b[39m\u001b[39msparse_categorical_crossentropy\u001b[39m\u001b[39m'\u001b[39m, optimizer\u001b[39m=\u001b[39m\u001b[39m'\u001b[39m\u001b[39madam\u001b[39m\u001b[39m'\u001b[39m, metrics\u001b[39m=\u001b[39m[\u001b[39m'\u001b[39m\u001b[39maccuracy\u001b[39m\u001b[39m'\u001b[39m])\n\u001b[1;32m     29\u001b[0m \u001b[39m# fit model\u001b[39;00m\n\u001b[0;32m---> 30\u001b[0m model\u001b[39m.\u001b[39;49mfit(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdataset\u001b[39m.\u001b[39;49mX_train\u001b[39m.\u001b[39;49mreshape(\u001b[39m-\u001b[39;49m\u001b[39m1\u001b[39;49m, \u001b[39m800\u001b[39;49m, \u001b[39m1\u001b[39;49m), \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdataset\u001b[39m.\u001b[39;49my_train, epochs\u001b[39m=\u001b[39;49mepochs, batch_size\u001b[39m=\u001b[39;49mbatch_size, validation_data\u001b[39m=\u001b[39;49m(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdataset\u001b[39m.\u001b[39;49mX_test\u001b[39m.\u001b[39;49mreshape(\u001b[39m-\u001b[39;49m\u001b[39m1\u001b[39;49m, \u001b[39m800\u001b[39;49m, \u001b[39m1\u001b[39;49m), \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mdataset\u001b[39m.\u001b[39;49my_test))\n",
      "File \u001b[0;32m/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     67\u001b[0m     filtered_tb \u001b[39m=\u001b[39m _process_traceback_frames(e\u001b[39m.\u001b[39m__traceback__)\n\u001b[1;32m     68\u001b[0m     \u001b[39m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[39m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m---> 70\u001b[0m     \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39mwith_traceback(filtered_tb) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39;00m\n\u001b[1;32m     71\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[1;32m     72\u001b[0m     \u001b[39mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/tensorflow/python/eager/execute.py:52\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     50\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m     51\u001b[0m   ctx\u001b[39m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 52\u001b[0m   tensors \u001b[39m=\u001b[39m pywrap_tfe\u001b[39m.\u001b[39mTFE_Py_Execute(ctx\u001b[39m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     53\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     54\u001b[0m \u001b[39mexcept\u001b[39;00m core\u001b[39m.\u001b[39m_NotOkStatusException \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m     55\u001b[0m   \u001b[39mif\u001b[39;00m name \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n",
      "\u001b[0;31mUnimplementedError\u001b[0m: Graph execution error:\n\nDetected at node 'sequential_1/conv1d_1/Conv1D' defined at (most recent call last):\n    File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n      exec(code, run_globals)\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/ipykernel_launcher.py\", line 17, in <module>\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/traitlets/config/application.py\", line 1043, in launch_instance\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/ipykernel/kernelapp.py\", line 725, in start\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/tornado/platform/asyncio.py\", line 215, in start\n    File \"/usr/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n      self._run_once()\n    File \"/usr/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n      handle._run()\n    File \"/usr/lib/python3.8/asyncio/events.py\", line 81, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 513, in dispatch_queue\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 502, in process_one\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 409, in dispatch_shell\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/ipykernel/zmqshell.py\", line 540, in run_cell\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3006, in run_cell\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3061, in _run_cell\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3266, in run_cell_async\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3445, in run_ast_nodes\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3505, in run_code\n    File \"/tmp/ipykernel_1360394/2310772659.py\", line 34, in <module>\n      data.cnn()\n    File \"/tmp/ipykernel_1360394/2310772659.py\", line 30, in cnn\n      model.fit(self.dataset.X_train.reshape(-1, 800, 1), self.dataset.y_train, epochs=epochs, batch_size=batch_size, validation_data=(self.dataset.X_test.reshape(-1, 800, 1), self.dataset.y_test))\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      except Exception as e:  # pylint: disable=broad-except\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1685, in fit\n      **kwargs: Unused at this time.\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1284, in train_function\n      only. Maximum number of processes to spin up\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1268, in step_function\n      Number of samples per validation batch.\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1249, in run_step\n      `tf.data` dataset, and 'steps_per_epoch'\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/training.py\", line 1050, in train_step\n      \"\"\"Runs a training execution with a single step.\"\"\"\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      except Exception as e:  # pylint: disable=broad-except\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/training.py\", line 558, in __call__\n      `y_pred` should have shape `(batch_size, d0, .. dN)`.\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      except Exception as e:  # pylint: disable=broad-except\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1145, in __call__\n      @input_spec.setter\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 96, in error_handler\n      raise e\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/sequential.py\", line 412, in call\n      for layer in super(Sequential, self).layers:\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 512, in call\n      # Layers expect shapes to be tuples for `compute_output_shape`.\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/functional.py\", line 669, in _run_internal_graph\n      try:\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      except Exception as e:  # pylint: disable=broad-except\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/engine/base_layer.py\", line 1145, in __call__\n      @input_spec.setter\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/utils/traceback_utils.py\", line 96, in error_handler\n      raise e\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/layers/convolutional/base_conv.py\", line 290, in call\n      ]\n    File \"/data/myenv/ECG-Stress-Classifier/.venv/lib/python3.8/site-packages/keras/layers/convolutional/base_conv.py\", line 262, in convolution_op\n      def _apply_fn(o):\nNode: 'sequential_1/conv1d_1/Conv1D'\nDNN library is not found.\n\t [[{{node sequential_1/conv1d_1/Conv1D}}]] [Op:__inference_train_function_1553]"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "from tensorflow import keras\n",
    "from tensorflow.keras import layers\n",
    "# from tensorflow.keras.metrics import binary_focal_crossentropy\n",
    "\n",
    "class Dataset:\n",
    "    def __init__(self):\n",
    "        # Generate random data for training and testing\n",
    "        self.X_train = np.random.rand(1000, 800)\n",
    "        self.y_train = np.random.randint(0, 3, size=(1000,))\n",
    "        self.X_test = np.random.rand(200, 800)\n",
    "        self.y_test = np.random.randint(0, 3, size=(200,))\n",
    "        \n",
    "    def cnn(self):\n",
    "        # Instantiate the Dataset class\n",
    "        self.dataset = Dataset()\n",
    "\n",
    "        verbose, epochs, batch_size = 0, 10, 32\n",
    "\n",
    "        model = keras.Sequential()\n",
    "        model.add(layers.Conv1D(filters=64, kernel_size=3, activation='relu', input_shape=(800, 1)))\n",
    "        model.add(layers.MaxPooling1D(pool_size=2))\n",
    "        model.add(layers.Flatten())\n",
    "        model.add(layers.Dense(units=3, activation='softmax'))\n",
    "\n",
    "        # compile model\n",
    "        model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])\n",
    "\n",
    "        # fit model\n",
    "        model.fit(self.dataset.X_train.reshape(-1, 800, 1), self.dataset.y_train, epochs=epochs, batch_size=batch_size, validation_data=(self.dataset.X_test.reshape(-1, 800, 1), self.dataset.y_test))\n",
    "\n",
    "\n",
    "data = Dataset()\n",
    "data.cnn()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.10"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
